// This function reads only the Histogram files generated by eBird.
// This is useful for seeing what birds have already been seen, but does not
// cover seeing all birds which might be seen or which have been seen outside
// of the area of the Histogram file.

import { fileURLToPath } from 'node:url'
import removeEmptyLines from 'remove-blank-lines'

async function getData (input) {
  const results = {}
  if (typeof input === 'string') {
    // Normalise CRLF first: remove-blank-lines would otherwise strip every "\n".
    const text = (await (await import('./io.js')).readText(input)).replace(/\r\n/g, '\n')
    input = removeEmptyLines(text).split('\n').filter(s => s.trim() !== '')
    results.taxa = input.filter(s => s.includes('Number of taxa'))[0].split('\t')[1]
    results.sampleSize = input.filter(s => s.includes('Sample Size'))[0].split('\t').slice(1).filter(x => x !== '')
    // Species rows are everything after the "Sample Size" line.
    input = input.slice(input.findIndex(s => s.includes('Sample Size')) + 1).map(species => {
      const dict = {}
      const speciesMatch = species.split('\t')[0].match(/(?<species>.*) \(.*>(?<latin>.*)</)
      const speciesName = speciesMatch.groups.species
      const scientificName = speciesMatch.groups.latin
      const frequency = species.split('\t').slice(1).filter(x => x !== '')
      // Basically, remove spuh
      const paraspecial = ['sp.', '/']
      if (!paraspecial.some(s => speciesName.includes(s))) {
        dict[speciesName] = {
          species: speciesName,
          'Scientific Name': scientificName,
          frequency
        }
        return dict
      }
      return null
    })
    results.species = input.filter(s => s !== null)
  }

  return results
}

// TODO Is there a way to automatically generate these? As in, download them each morning from eBird?
async function washingtonCounty2020 () {
  return await getData(fileURLToPath(new URL('./data/ebird_US-VT-023__2020_2020_1_12_barchart.txt', import.meta.url)))
}

export {
  washingtonCounty2020
}

export default {
  washingtonCounty2020
}
